spring:
  application: ia-market
  mvc:
    static-path-pattern: "/**"

anymarket:
  base-url: https://app.anymarket.com.br
  token: 259029268L22449504E1790198813829C169688681382900O1.I

sandbox:
    base-url: https://api.anymarket.com.br
    token: MjI0NDk1MDQu.DLgBmWACSIJ+ZnLnVrtWXkOPdgGnRKay8HfDKv/3sMulNsFPft176plbOttnqpeie/Ry+2n+nsXdeq3TidP4qA==

openapi:
  url: https://api.openai.com/v1
  token: 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


